### ISSUE TITLE
Url with no extension?

### ISSUE THREAD

**Issue by sinnbeck** [spatie/laravel-google-fonts#40]
Suddenly today I am getting an error as the package is getting this url back without an extension.

https://fonts.gstatic.com/l/font?kit=XRXI3I6Li01BKofiOc5wtlZ2di8HDLshdTA3iazbXWjgevT5&skey=27bb6aa8eea8a5e7&v=v26

 It is a woff file but `GoogleFonts::localizeFontUrl()` expects it to have an extension and therefor throws a 500 error. It seems to happen quite randomly, and if I run my test suite it happens at least once.

If I check the font files in the storage directory I dont find this url anywhere, so I expect it comes directly from google.
Is it perhaps possible to ensure it does not query google in tests at all (even if not preloaded)?

**Comment by sinnbeck** [comment]
After several attempts with xdebug I finally was able to get the content of $css in `GoogleFonts::fetch()`

```css
/* cyrillic-ext */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/l/font?kit=XRXI3I6Li01BKofiOc5wtlZ2di8HDLshdTk3iazbXWjgevT5&skey=27bb6aa8eea8a5e7&v=v26) format('woff');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/l/font?kit=XRXI3I6Li01BKofiOc5wtlZ2di8HDLshdTA3iazbXWjgevT5&skey=27bb6aa8eea8a5e7&v=v26) format('woff');
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* vietnamese */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/nunito/v26/XRXI3I6Li01BKofiOc5wtlZ2di8HDLshdTs3iazbXWjgevT5.woff) format('woff');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/nunito/v26/XRXI3I6Li01BKofiOc5wtlZ2di8HDLshdTo3iazbXWjgevT5.woff) format('woff');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/nunito/v26/XRXI3I6Li01BKofiOc5wtlZ2di8HDLshdTQ3iazbXWjgeg.woff) format('woff');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

**Comment by sebastiandedeyne** [comment]
Can you share the Google Fonts URL you're using to load fonts?

**Comment by sinnbeck** [comment]
Sure :) Its this https://fonts.googleapis.com/css?family=Nunito

But as I said it seems to happen at random. I had force download for this font which made it redownload every time, which cause issues like 1-10 time it downloaded. Just a suggestion to perhaps just have it do a fallback to .woff if no extension is found or similar :)

**Comment by sebastiandedeyne** [comment]
Interesting, haven't come across this during testing. I agree it should fall back to providing an extension based on the `format` function in the CSS property.

I currently don't have time to work on this, but contributions welcome!
