### ISSUE TITLE
New Preload Breaks Existing Config

### ISSUE THREAD

**Issue by freshleafmedia** [spatie/laravel-google-fonts#44]
Any existing project which has overridden the default config will break when upgrading to 1.3.0 due to the new preload flag not having a value and defaulting to `null` when it is required to be a `bool`.

```
TypeError: Spatie\GoogleFonts\GoogleFonts::__construct(): Argument #7 ($preload) must be of type bool, null given, called in //vendor/spatie/laravel-google-fonts/src/GoogleFontsServiceProvider.php on line 25
```

Updating the project config to include the `preload` key fixes this. Suggest adding a default `false` value for this new key

**Comment by sebastiandedeyne** [comment]
Pushed a hotfix to fall back to a boolean when the setting is not provided. Thanks for the heads up!
